# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local ]

instances:
  - id: oem-prepare
    module: shellprocess
    config: shellprocess-oem-prepare.conf
  - id: oem-finalize
    module: shellprocess
    config: shellprocess-oem-finalize.conf

sequence:
  - show: [ users, summary ]
  - exec: [ shellprocess@oem-prepare, users, displaymanager, shellprocess@oem-finalize ]
  - show: [ finished ]

branding: default
prompt-install: true
dont-chroot: true
oem-setup: true
disable-cancel: true
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
