# SPDX-License-Identifier: CC0-1.0
---
displaymanagers: [ sddm ]
defaultDesktopEnvironment:
  executable: /usr/bin/startplasmamobile
  desktopFile: plasma-mobile
basicSetup: false
sysconfigSetup: false
sddm:
  configuration_file: /etc/sddm.conf.d/90-m1892-oem-account.conf
