# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 30
verbose: true
script:
  - command: "/usr/libexec/m1892/oem-owner-finalize ${USER}"
    timeout: 30
i18n:
  name: "Finalize the M1892 owner account"
  name[zh_CN]: "完成 M1892 机主账户设置"
